services:
  app:
    image: automaticbytes/demo-app
    ports:
      - "3100:3100"
    networks:
      - test-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3100",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  tests:
    build: .
    platform: linux/amd64
    depends_on:
      app:
        condition: service_healthy
    networks:
      - test-network
    environment:
      - PLAYWRIGHT_BASE_URL=http://app:3100
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report

networks:
  test-network:
    driver: bridge
